#ifndef EXASOCK_KERNEL_CONSTS_H
#define EXASOCK_KERNEL_CONSTS_H

#define EXA_TCP_MSS 1460
#define EXA_TCP_WSCALE 8
#define EXA_TCP_SYNACK_WIN 32000
#define EXA_TCP_FAST_RETRANS_THRESH 3

#endif /* EXASOCK_KERNEL_CONSTS_H */
